#!/usr/bin/env python
# -*- mode: python -*-

#   Copyright (c) 2001       Jason Gunthorpe <jgg@debian.org>
#   Copyright (c) 2004       Joey Schulze <joey@debian.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

import string, re, time, ldap, getopt, sys, pwd, os, posix;
from userdir_ldap import *;

# Main program starts here
User = pwd.getpwuid(posix.getuid())[0];
BindUser = User;
(options, arguments) = getopt.getopt(sys.argv[1:], "au:")
for (switch, val) in options:
    if (switch == '-u'):
	User = val;
    if (switch == '-a'):
	Anon = 1;
			      
# Connect to the ldap server
l = passwdAccessLDAP(LDAPServer, BaseDn, User)

Attrs = l.search_s(BaseDn,ldap.SCOPE_ONELEVEL,"userpassword=*",\
         ["uid","cn","mn","sn","userpassword"]);

Attrs.sort();
for x in Attrs:
    if x[1].has_key("userpassword") == 0: continue;
    Passwd = x[1]["userpassword"][0];
    if string.find(Passwd,"*LK*") != -1 or string.find(Passwd,"}*") != -1:
	continue;
    if len(Passwd) > 21: continue;
    
    print EmailAddress(x);

    UserDn = "uid=" + x[1]["uid"][0] + "," + BaseDn;
    Password = GenPass();
    Pass = "{crypt}" + HashPass(Password);
    l.modify_s(UserDn,[(ldap.MOD_REPLACE,"userpassword",Pass)]);
