#! /bin/bash -e
#
#DEBHELPER#
if [ "$1" = "configure" ]
then
    test ! -f /usr/local/bin/ud-replicate || rm -f /usr/local/bin/ud-replicate

    if ! [ -e /var/lib/misc/thishost ]; then
	ln -s "`hostname`" /var/lib/misc/thishost
    fi
fi
exit 0
