#! /bin/bash -e
#
# Debian prerm script for Python 1.5 hierarchical modules
# Written by Gregor Hoffleit <flight@debian.org>
#

NAME=userdir-ldap

dpkg --listfiles $NAME |
	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
	xargs rm -f >&2

if command -v install-docs >/dev/null 2>&1; then
    install-docs -r $NAME
fi
